# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_receivings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='verification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='document_receivings.Verification'),
        ),
    ]
