# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_receivings', '0002_auto_20161122_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verification',
            options={'permissions': (('can_verify', 'Can Verify Document'),)},
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Verified'), (2, 'Rejected')], default=0),
        ),
    ]
